### PR TITLE
added additional superclass call

### PR DESCRIPTION
**Pull request by russ1985**
Not sure if you ran into this with Sencha Touch 2.4.\* but I had to add an additional superclass call to get it to work

thanks,

### CODE REVIEW

**Comment by vadimpopa** [comment]
So what's the issue ? I've tried the fiddle https://fiddle.sencha.com/#fiddle/r9 and seems ok

**Comment by russ1985** [comment]
Maybe it was just my setup, I am using Sencha Touch 2.4.1 and I have a field that is extending from your field.  Maybe because I was extending the field I needed the additional superclass call.

**Comment by vadimpopa** [comment]
Right, if you extend it, then you need to call one more superClass. Because this is a component which is rarely extended, I will just add a comment in the code, don't want to write a loop and get the Ext.field.Text superclass which actually ends the updateValue. Thanks for raising this.

**Comment by russ1985** [comment]
Makes sense, thanks!


Sent via the Samsung Galaxy S™ III, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Vadim Popa <notifications@github.com> </div><div>Date:07/04/2015  16:09  (GMT-05:00) </div><div>To: "vadimpopa/Ux.field.Multiselect" <Ux.field.Multiselect@noreply.github.com> </div><div>Cc: Russell Holmes <rholmes@truenorthtechnology.com> </div><div>Subject: Re: [Ux.field.Multiselect] added additional superclass call (#7) </div><div>
</div>Right, if you extend it, then you need to call one more superClass. Because this is a component which is rarely extended, I will just add a comment in the code, don't want to write a loop and get the Ext.field.Text superclass which actually ends the updateValue. Thanks for raising this.

**Comment by waqarprojectinertia** [comment]
Hey
Does it work in extjs 6 modern toolkit? or any other plugin

**Pull request closed without merging**
